attributes:
  fuel-plugin-calamari_username:
    value: "admin"
    label: "Admin Username"
    description: "Calamari Admin Username"
    weight: 25
    type: "text"
    regex:
      source: '^[\S]{4,}$'
      error: "You must provide an username with at least 4 characters"
  fuel-plugin-calamari_password:
    value: "admin"
    label: "Admin Password"
    description: "Calamari Admin Password"
    weight: 25
    type: "password"
    regex:
      source: '^[\S]{4,}$'
      error: "You must provide a password with at least 4 characters"
  fuel-plugin-calamari_email:
    value: "admin@localhost.invalid"
    label: "Admin Email"
    description: "Calamari Admin Email"
    weight: 40
    type: "text"
    regex:
      source: '^\S+@\S+$'
      error: "Invalid email"